/*
 * gen_tables.c -- computes, with IEEE single precision exactly like the game,
 * how many frames each timer stays positive, and a few derived tables. The
 * solver model uses these integer counters instead of float timers; the
 * reference build (-DREFERENCE) keeps the float timers, and tests/diff.sh
 * checks the two agree frame by frame.
 *
 * Every timer in the model is only ever (a) set to a constant, (b) set to 0,
 * (c) decremented by DeltaTime while positive, and (d) compared with 0 --
 * except varJumpTimer (compared with VarJumpTime - CeilingVarJumpGrace) and
 * wallSlideTimer (its value feeds a Lerp), which get extra tables.
 */
#include <stdio.h>
#include "celeste.h"

static int frames_positive(float c)
{
    volatile float t = c;
    int k = 0;
    while (t > 0) { t = t - DT; k++; }
    return k;
}

/* frames (decrements) until the timer drops below `thr` */
static int frames_until_below(float c, float thr)
{
    volatile float t = c;
    int k = 0;
    while (!(t < thr)) { t = t - DT; k++; }
    return k;
}

#define K(name) printf("#define K_%s %d\n", #name, frames_positive(name))

int main(void)
{
    printf("/* generated by tools/gen_tables.c -- do not edit */\n");
    printf("#ifndef TABLES_H\n#define TABLES_H\n");
    K(JUMP_GRACE_TIME);
    K(VAR_JUMP_TIME);
    K(SUPER_WALL_JUMP_VAR_TIME);
    K(DASH_COOLDOWN);
    K(DASH_REFILL_COOLDOWN);
    K(DASH_ATTACK_TIME);
    K(WALL_SPEED_RETENTION_TIME);
    K(WALL_JUMP_FORCE_TIME);
    K(DASH_TIME);
    K(DASH_FREEZE_TIME);
    K(INPUT_BUFFER_TIME);
    K(CLIMB_NO_MOVE_TIME);
    K(CLIMB_HOP_FORCE_TIME);
    K(CLIMB_JUMP_BOOST_TIME);
    K(SUPER_BOUNCE_VAR_JUMP_TIME);
    K(REBOUND_VAR_JUMP_TIME);
    K(LIFT_SPEED_GRACE_TIME);
    K(REFILL_RESPAWN_TIME);

    /* varJumpTimer < VarJumpTime - CeilingVarJumpGrace  <=>  remaining <= VJ_* */
    const float thr = VAR_JUMP_TIME - CEILING_VAR_JUMP_GRACE;
    printf("#define VJ_VAR_JUMP_TIME %d\n",
           frames_positive(VAR_JUMP_TIME) - frames_until_below(VAR_JUMP_TIME, thr));
    printf("#define VJ_SUPER_WALL_JUMP_VAR_TIME %d\n",
           frames_positive(SUPER_WALL_JUMP_VAR_TIME) - frames_until_below(SUPER_WALL_JUMP_VAR_TIME, thr));
    printf("#define VJ_REBOUND_VAR_JUMP_TIME %d\n",
           frames_positive(REBOUND_VAR_JUMP_TIME) - frames_until_below(REBOUND_VAR_JUMP_TIME, thr));

    /* wallSlideTimer: steps k since set to WallSlideTime, clamped at 0 */
    {
        volatile float t = WALL_SLIDE_TIME;
        int kz = 0;
        float vals[256];
        for (;;) {
            vals[kz] = t;
            if (!(t > 0)) break;
            float n = t - DT;
            t = n > 0 ? n : 0;      /* Math.Max(t - dt, 0) */
            kz++;
        }
        printf("#define WS_KZ %d /* steps until wallSlideTimer == 0 */\n", kz);
        printf("static const float WS_LERP_MAX[%d] = {\n", kz + 1);
        for (int k = 0; k <= kz; k++) {
            volatile float amount = vals[k] / WALL_SLIDE_TIME;
            volatile float prod = (WALL_SLIDE_START_MAX - MAX_FALL) * amount;
            volatile float v = MAX_FALL + prod;  /* MathHelper.Lerp(MaxFall, WallSlideStartMax, t / WallSlideTime) */
            printf("    %.9ef,%s", (double)v, (k % 4 == 3) ? "\n" : "");
        }
        printf("\n};\n");
    }
    printf("#endif\n");
    return 0;
}
